# WeatherPy
----

### Analysis
* As expected, the weather becomes significantly warmer as one approaches the equator (0 Deg. Latitude). More interestingly, however, is the fact that the southern hemisphere tends to be warmer this time of year than the northern hemisphere. This may be due to the tilt of the earth.
* There is no strong relationship between latitude and cloudiness. However, it is interesting to see that a strong band of cities sits at 0, 80, and 100% cloudiness.
* There is no strong relationship between latitude and wind speed. However, in northern hemispheres there is a flurry of cities with over 20 mph of wind.

---

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time





# Import API key
from api_keys import api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)
settings = {"units": "Imperial", "appid": api_key}

## Generate Cities List

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1])
   
    city_n = city.city_name + "," + city.country_code
    # If the city is unique, then add it to a our cities list
    if city_n not in cities:
        cities.append(city_n)

# Print the city count to confirm sufficient count
len(cities)

637

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [ ]:

#url= "http://api.openweathermap.org/data/2.5/weather?"
#query_url= f"{url}appid={api_key}&q="
url="http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + api_key
#print(url)
city_name = []
cloudiness = []
country = []
date = []
humidity = []
lat = []
lng = []
max_temp = []
wind_speed = []
count = 1
print(f"Beginning Data Retrieval")
print(f"-------------------------------")
for city in cities:
    try:
        response = requests.get(f"{url}&q={city}").json()
        city_name.append(response["name"])
        cloudiness.append(response["clouds"]["all"])
        country.append(response["sys"]["country"])
        date.append(response["dt"])
        humidity.append(response["main"]["humidity"])
        max_temp.append(response["main"]["temp_max"])
        lat.append(response["coord"]["lat"])
        lng.append(response["coord"]["lon"])
        wind_speed.append(response["wind"]["speed"])
        city_record = response["name"]
        print(f"Processing Record {count} | {city_record}")
        print(f"{url}&q={city}")
        count= count + 1
        time.sleep(1.01)
    except:
        print("City Not found..Next")
        continue
print(f"-------------------------------")
print(f"Data Retrieval Complete")
print(f"-------------------------------")

Beginning Data Retrieval
-------------------------------
Processing Record 1 | Mitsamiouli
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=mitsamiouli,km
Processing Record 2 | Jamestown
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=jamestown,sh
Processing Record 3 | Kapaa
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=kapaa,us
Processing Record 4 | Marovoay
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=marovoay,mg
Processing Record 5 | Sakaraha
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=sakaraha,mg
Processing Record 6 | Kumul
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=hami,cn
Processing Record 7 | Hithadhoo
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=hithadhoo,mv
Processing Record 8 | Birjand
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=birjand,ir
Processing Record 9 | Dikson
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=dikson,ru
Processing Record 10 | Khatanga
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=khatanga,ru
City Not found..Next
Processing Record 11 | Nanortalik
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=nanortalik,gl
Processing Record 12 | Yārāda
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=yarada,in
Processing Record 13 | Huicungo
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=huicungo,pe
Processing Record 14 | Butaritari
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=butaritari,ki
Processing Record 15 | Vredendal
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=vredendal,za
Processing Record 16 | Bolobo
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=bolobo,cd
Processing Record 17 | Guerrero Negro
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=guerrero negro,mx
Processing Record 18 | Tuatapere
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=tuatapere,nz
Processing Record 19 | Esperance
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=esperance,au
Processing Record 20 | Punta Arenas
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=punta arenas,cl
Processing Record 21 | Tasiilaq
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=tasiilaq,gl
Processing Record 22 | Lompoc
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=lompoc,us
Processing Record 23 | Nikolskoye
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=nikolskoye,ru
Processing Record 24 | Puerto Ayora
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=puerto ayora,ec
Processing Record 25 | Cabo San Lucas
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=cabo san lucas,mx
Processing Record 26 | Vuktyl
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=vuktyl,ru
City Not found..Next
City Not found..Next
Processing Record 27 | Verāval
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=veraval,in
Processing Record 28 | Ibanda
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=ibanda,ug
Processing Record 29 | Clyde River
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=clyde river,ca
Processing Record 30 | Ushuaia
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=ushuaia,ar
Processing Record 31 | Sur
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=sur,om
Processing Record 32 | Rikitea
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=rikitea,pf
Processing Record 33 | Broken Hill
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=broken hill,au
Processing Record 34 | Yumen
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=yumen,cn
Processing Record 35 | Eureka
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=eureka,us
Processing Record 36 | Labuhan
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=labuhan,id
City Not found..Next
Processing Record 37 | Jambi City
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=jambi,id
Processing Record 38 | Magdagachi
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=magdagachi,ru
Processing Record 39 | Geraldton
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=geraldton,au
Processing Record 40 | Baharly
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=baherden,tm
City Not found..Next
Processing Record 41 | Padang
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=padang,id
City Not found..Next
Processing Record 42 | Novopavlovka
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=novopavlovka,ru
Processing Record 43 | Dongli
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=dongli,cn
Processing Record 44 | Hilo
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=hilo,us
Processing Record 45 | Avarua
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=avarua,ck
Processing Record 46 | Kimbe
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=kimbe,pg
Processing Record 47 | Cape Town
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=cape town,za
Processing Record 48 | Castro
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=castro,cl
Processing Record 49 | Kruisfontein
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=kruisfontein,za
Processing Record 50 | Jalu
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=jalu,ly
Processing Record 51 | Busselton
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=busselton,au
City Not found..Next
Processing Record 52 | Arman'
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=arman,ru
City Not found..Next
Processing Record 53 | Severo-Kuril'sk
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=severo-kurilsk,ru
Processing Record 54 | Isangel
http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=24bdeac8a81ffc1d1a9eee0125b0a5f8&q=isangel,vu

In [28]:
weather_df=pd.DataFrame(
{'City': city_name,
 'Country': country,
 'Date': date,
 'Latitude': lat,
 'Longtitude': lng,
 'Cloudiness': cloudiness,
 'Humidity': humidity,
 'Max_temp': max_temp,
 'Wind_speed': wind_speed
 }
)

In [29]:
weather_df

,City,Country,Date,Latitude,Longtitude,Cloudiness,Humidity,Max_temp,Wind_speed
0,Butaritari,KI,1604768597,3.07,172.79,100,75,80.60,11.27
1,Balakliya,UA,1604768598,49.46,36.86,0,87,46.40,8.95
2,Kindu,CD,1604768600,-2.95,25.95,98,91,73.06,0.89
3,Hokitika,NZ,1604768602,-42.72,170.97,100,87,48.92,9.31
4,Rikitea,PF,1604768604,-23.12,-134.97,75,75,71.26,19.69
...,...,...,...,...,...,...,...,...,...
556,Marsabit,KE,1604769826,2.33,37.99,50,84,67.73,11.70
557,Muswellbrook,AU,1604769827,-32.27,150.90,88,75,57.99,1.99
558,Aykhal,RU,1604769829,66.00,111.50,0,84,-0.40,6.71
559,Cherskiy,RU,1604769801,68.75,161.30,95,95,6.08,6.53
560,Krasnaya Gorka,RU,1604769833,55.20,56.67,100,92,37.40,5.14

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [30]:

weather_df.to_csv (r'C:\Users\glenn\Documents\cities.csv', index = False, header=True)

weather_df

,City,Country,Date,Latitude,Longtitude,Cloudiness,Humidity,Max_temp,Wind_speed
0,Butaritari,KI,1604768597,3.07,172.79,100,75,80.60,11.27
1,Balakliya,UA,1604768598,49.46,36.86,0,87,46.40,8.95
2,Kindu,CD,1604768600,-2.95,25.95,98,91,73.06,0.89
3,Hokitika,NZ,1604768602,-42.72,170.97,100,87,48.92,9.31
4,Rikitea,PF,1604768604,-23.12,-134.97,75,75,71.26,19.69
...,...,...,...,...,...,...,...,...,...
556,Marsabit,KE,1604769826,2.33,37.99,50,84,67.73,11.70
557,Muswellbrook,AU,1604769827,-32.27,150.90,88,75,57.99,1.99
558,Aykhal,RU,1604769829,66.00,111.50,0,84,-0.40,6.71
559,Cherskiy,RU,1604769801,68.75,161.30,95,95,6.08,6.53
560,Krasnaya Gorka,RU,1604769833,55.20,56.67,100,92,37.40,5.14

### Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

#### Latitude vs. Temperature Plot

In [1]:
plt.scatter(weather_df['Latitude'],weather_df['Max_temp'])
plt.title("Effect of Latitude to Temperature")
plt.xlabel("Latitude (degrees N is positive)")
plt.ylabel("Maximum Temperature (F)")
plt.xlim(-80,80)
plt.show

NameError: name 'plt' is not defined

#### Latitude vs. Humidity Plot

In [ ]:
plt.scatter(weather_df['Latitude'],weather_df['Humidity'])
plt.title("Effect of Latitude on Cloudiness")
plt.xlabel("Latitude (degrees N is positive)")
plt.ylabel('Humidity')
plt.xlim(-80,80)
plt.show

#### Latitude vs. Cloudiness Plot

In [ ]:
plt.scatter(weather_df['Latitude'],weather_df['Cloudiness'])
plt.title("Effect of Latitude on Cloudiness")
plt.xlabel("Latitude (degrees N is positive)")
plt.ylabel("Cloud Cover (%)")
plt.xlim(-80,80)
plt.show

#### Latitude vs. Wind Speed Plot

In [ ]:
plt.scatter(weather_df['Latitude'],weather_df['Wind Speed'])
plt.title("Effect of Latitude on Wind")
plt.xlabel("Latitude (degrees N is positive)")
plt.ylabel("Wind Speed (mpH)")
plt.xlim(-80,80)
plt.show